
Prompt Index PK_REINF_CF_PREVIDENCIARIA_TMP;
--
-- PK_REINF_CF_PREVIDENCIARIA_TMP  (Index) 
--
CREATE UNIQUE INDEX  PK_FIN4816_REINF_CONF_PREV ON MSAFI.TB_FIN4816_REINF_CONF_PREV_GTT
(COD_EMPRESA, COD_ESTAB, DATA_EMISSAO, DATA_FISCAL, IDENT_FIS_JUR, 
IDENT_DOCTO, NUM_DOCFIS, SERIE_DOCFIS, SUB_SERIE_DOCFIS, NUM_ITEM, 
COD_USUARIO);

/

-- 
-- Non Foreign Key Constraints for Table REINF_CONF_PREVIDENCIARIA_TMP 
-- 
Prompt Non-Foreign Key Constraints on Table REINF_CONF_PREVIDENCIARIA_TMP;
ALTER TABLE  MSAFI.TB_FIN4816_REINF_CONF_PREV_GTT ADD (
  CONSTRAINT PK_FIN4816_REINF_CONF_PREV
  PRIMARY KEY
  (COD_EMPRESA, COD_ESTAB, DATA_EMISSAO, DATA_FISCAL, IDENT_FIS_JUR, IDENT_DOCTO, NUM_DOCFIS, SERIE_DOCFIS, SUB_SERIE_DOCFIS, NUM_ITEM, COD_USUARIO)
  USING INDEX PK_FIN4816_REINF_CONF_PREV
  ENABLE VALIDATE)
/
