Prompt Table TB_FIN4816_PREV_TMP_ESTAB;
--
-- TB_FIN4816_PREV_TMP_ESTAB  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE msafi.tb_fin4816_prev_tmp_estab
(
  PROC_ID    INTEGER,
  COD_ESTAB  VARCHAR2(6 BYTE),
  NR_GRUPO   INTEGER,
  DT_CARGA   VARCHAR2(20 BYTE)
)
ON COMMIT PRESERVE ROWS
NOCACHE
/
