
DROP TABLE msafi.fin4816_reinf_prev_gtt

CREATE TABLE msafi.fin4816_reinf_prev_gtt
(
  COD_EMPRESA              VARCHAR2(3 BYTE)     NOT NULL,
  COD_ESTAB                VARCHAR2(6 BYTE)     NOT NULL,
  DATA_EMISSAO             DATE                 NOT NULL,
  DATA_FISCAL              DATE                 NOT NULL,
  IDENT_FIS_JUR            NUMBER(12)           NOT NULL,
  IDENT_DOCTO              NUMBER(12)           NOT NULL,
  NUM_DOCFIS               VARCHAR2(12 BYTE)    NOT NULL,
  SERIE_DOCFIS             VARCHAR2(3 BYTE)     NOT NULL,
  SUB_SERIE_DOCFIS         VARCHAR2(2 BYTE)     NOT NULL,
  NUM_ITEM                 NUMBER(5)            NOT NULL,
  COD_USUARIO              VARCHAR2(35 BYTE)    NOT NULL,
  --  
  TIPO                   CHAR(1 BYTE),
  COD_FIS_JUR            VARCHAR2(14 BYTE),
  X04_RAZAO_SOCIAL       VARCHAR2(100 BYTE),
  IND_FIS_JUR            CHAR(1 BYTE),
  CPF_CGC                VARCHAR2(14 BYTE),
  COD_CLASS_DOC_FIS      CHAR(1 BYTE),
  VLR_TOT_NOTA           NUMBER(17,2),
  VLR_BASE_INSS          NUMBER(17,2),
  VLR_ALIQ_INSS          NUMBER(7,4),
  VLR_INSS_RETIDO        NUMBER(17,2),
  VLR_CONTAB_COMPL       NUMBER(17,2),
  IND_TIPO_PROC          CHAR(1 BYTE),
  NUM_PROC_JUR           VARCHAR2(21 BYTE),
  RAZAO_SOCIAL           VARCHAR2(100 BYTE),
  CGC                    VARCHAR2(14 BYTE),
  DESCRICAO              VARCHAR2(50 BYTE),
  COD_TIPO_SERV_ESOCIAL  VARCHAR2(10 BYTE),
  DSC_TIPO_SERV_ESOCIAL  VARCHAR2(100 BYTE),
  EMPRESA_RAZAO_SOCIAL   VARCHAR2(70 BYTE),
  VLR_SERVICO            NUMBER(17,2),
  NUM_PROC_ADJ_ADIC      VARCHAR2(21 BYTE),
  IND_TP_PROC_ADJ_ADIC   CHAR(1 BYTE),
  CODIGO_SERV_PROD       VARCHAR2(35 BYTE),
  DESC_SERV_PROD         VARCHAR2(50 BYTE)
  );
  
  

Prompt Index IDX_REINF_PREV;
--
-- IDX_REINF_PREV  (Index) 
--
CREATE UNIQUE INDEX IDX_REINF_PREV ON MSAFI.FIN4816_REINF_PREV_GTT
(COD_EMPRESA, COD_ESTAB, DATA_EMISSAO, DATA_FISCAL, IDENT_FIS_JUR, 
IDENT_DOCTO, NUM_DOCFIS, SERIE_DOCFIS, SUB_SERIE_DOCFIS, NUM_ITEM, 
COD_USUARIO)
LOGGING
/

-- 
-- Non Foreign Key Constraints for Table FIN4816_REINF_PREV_GTT 
-- 
Prompt Non-Foreign Key Constraints on Table FIN4816_REINF_PREV_GTT;
ALTER TABLE MSAFI.FIN4816_REINF_PREV_GTT ADD (
  CONSTRAINT idx_reinf_prev
  PRIMARY KEY
  (COD_EMPRESA, COD_ESTAB, DATA_EMISSAO, DATA_FISCAL, IDENT_FIS_JUR, IDENT_DOCTO, NUM_DOCFIS, SERIE_DOCFIS, SUB_SERIE_DOCFIS, NUM_ITEM, COD_USUARIO)
  USING INDEX IDX_REINF_PREV
  ENABLE VALIDATE)
/
