Prompt Table DPSP_FIN048_RET_COMPETE;
--
-- DPSP_FIN048_RET_COMPETE  (Table) 
--
CREATE TABLE MSAFI.DPSP_FIN048_RET_COMPETE
(
  COD_ESTAB          VARCHAR2(6 BYTE)           NOT NULL,
  UF_ESTAB           VARCHAR2(2 BYTE),
  UF_FORN_CLI        VARCHAR2(2 BYTE),
  DATA_FISCAL        DATE                       NOT NULL,
  NUMERO_NF          VARCHAR2(12 BYTE)          NOT NULL,
  SERIE              VARCHAR2(3 BYTE)           NOT NULL,
  ID_PEOPLE          VARCHAR2(12 BYTE),
  COD_DOCTO          VARCHAR2(5 BYTE),
  COD_MODELO         VARCHAR2(2 BYTE),
  FIN                VARCHAR2(3 BYTE),
  COD_CFO            VARCHAR2(4 BYTE),
  CST                VARCHAR2(2 BYTE),
  VLR_CONTABIL       NUMBER,
  BASE_TRIB          NUMBER,
  ALIQ_TRIBUTO_ICMS  NUMBER(7,4),
  VLR_ICMS           NUMBER,
  BASE_ISENT         NUMBER,
  BASE_OUTRAS        NUMBER,
  BASE_RED           NUMBER,
  VLR_ICMS_ST        NUMBER,
  VLR_IPI            NUMBER,
  DIF_BASES          NUMBER,
  PROC_ID            INTEGER,
  NM_USUARIO         VARCHAR2(50 BYTE),
  DT_CARGA           VARCHAR2(20 BYTE)
)
LOGGING 
ROW STORE COMPRESS BASIC
NOCACHE
MONITORING
/
