Prompt Table DPSP_FIN048_RET_NF_SAI;
--
-- DPSP_FIN048_RET_NF_SAI  (Table) 
--
CREATE TABLE MSAFI.DPSP_FIN048_RET_NF_SAI
(
  COD_EMPRESA         VARCHAR2(3 BYTE)          NOT NULL,
  COD_ESTAB           VARCHAR2(6 BYTE)          NOT NULL,
  DATA_FISCAL         DATE                      NOT NULL,
  NUM_DOCFIS          VARCHAR2(12 BYTE)         NOT NULL,
  NUM_CONTROLE_DOCTO  VARCHAR2(12 BYTE),
  NUM_AUTENTIC_NFE    VARCHAR2(80 BYTE),
  COD_FIS_JUR         VARCHAR2(14 BYTE),
  CPF_CGC             VARCHAR2(14 BYTE),
  COD_DOCTO           VARCHAR2(5 BYTE),
  COD_MODELO          VARCHAR2(2 BYTE),
  COD_CFO             VARCHAR2(4 BYTE),
  COD_PRODUTO         VARCHAR2(35 BYTE),
  DESCRICAO           VARCHAR2(50 BYTE),
  NUM_ITEM            NUMBER(5),
  VLR_CONTABIL_ITEM   NUMBER(17,2),
  VLR_ITEM            NUMBER(17,2),
  VLR_BASE_ICMS_1     NUMBER(17,2),
  VLR_BASE_ICMS_2     NUMBER(17,2),
  VLR_BASE_ICMS_3     NUMBER(17,2),
  VLR_BASE_ICMS_4     NUMBER(17,2),
  VLR_IPI_NDESTAC     NUMBER(17,2),
  VLR_DESCONTO        NUMBER(17,2),
  ALIQ_TRIBUTO_ICMS   NUMBER(7,4),
  VLR_ICMS_ST         NUMBER(17,2),
  VLR_BASE_ST         NUMBER(17,2),
  VLR_ICMS_PROPRIO    NUMBER(17,2),
  CST                 VARCHAR2(2 BYTE),
  QUANTIDADE          NUMBER(17,6),
  NCM                 VARCHAR2(10 BYTE),
  MVA                 NUMBER(5,2),
  PMC_PAUTA           NUMBER(12,2),
  TP_CALC             VARCHAR2(40 BYTE),
  SIT_TRIB            VARCHAR2(40 BYTE),
  PERC_RED_BSST       NUMBER(5,2),
  FINALIDADE          VARCHAR2(3 BYTE),
  ALIQUOTA_INTERNA    NUMBER,
  VLR_UNIT_ITEM       NUMBER(17,2),
  ICMS_PROPRIO        NUMBER(17,2),
  BC_ICMS_ST          NUMBER(17,2),
  ICMS_ST             NUMBER(17,2),
  COD_ESTADO_TO       VARCHAR2(2 BYTE),
  COD_ESTADO_FROM     VARCHAR2(2 BYTE),
  PROC_ID             INTEGER,
  NM_USUARIO          VARCHAR2(50 BYTE),
  DT_CARGA            VARCHAR2(20 BYTE),
  SERIE_DOCFIS        VARCHAR2(20 BYTE),
  COD_NATUREZA_OP     VARCHAR2(20 BYTE)
)
LOGGING 
ROW STORE COMPRESS BASIC
NOCACHE
MONITORING
/


Prompt Index IDX_FIN48_SAIDA;
--
-- IDX_FIN48_SAIDA  (Index) 
--
CREATE INDEX IDX_FIN48_SAIDA ON MSAFI.DPSP_FIN048_RET_NF_SAI
(COD_EMPRESA, COD_ESTAB, DATA_FISCAL, NUM_DOCFIS, NUM_CONTROLE_DOCTO, 
NUM_AUTENTIC_NFE, COD_FIS_JUR, CPF_CGC, NUM_ITEM, COD_PRODUTO)
LOGGING
/
