Prompt Table X07_DOCTO_FISCAL_GTT;
--
-- X07_DOCTO_FISCAL_GTT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE MSAFI.X07_DOCTO_FISCAL_GTT
(
  COD_EMPRESA             VARCHAR2(3 BYTE)      NOT NULL,
  COD_ESTAB               VARCHAR2(6 BYTE)      NOT NULL,
  DATA_FISCAL             DATE                  NOT NULL,
  MOVTO_E_S               CHAR(1 BYTE)          NOT NULL,
  NORM_DEV                CHAR(1 BYTE)          NOT NULL,
  IDENT_DOCTO             NUMBER(12)            NOT NULL,
  IDENT_FIS_JUR           NUMBER(12)            NOT NULL,
  NUM_DOCFIS              VARCHAR2(12 BYTE)     NOT NULL,
  SERIE_DOCFIS            VARCHAR2(3 BYTE)      NOT NULL,
  SUB_SERIE_DOCFIS        VARCHAR2(2 BYTE)      NOT NULL,
  NUM_ITEM                NUMBER,
  ROWID_X07               ROWID,
  VALOR_ALIQUOTA_ORIGEM   NUMBER,
  VALOR_BASE_ICMS_ORIGEM  NUMBER,
  VALOR_ICMS_ORIGEM       NUMBER,
  FIN48_VLR_ITEM          NUMBER(17,2),
  VLR_BASE_ICMS_3         NUMBER(17,2),
  VLR_BASE_ICMS_2         NUMBER(17,2),
  VLR_BASE_ICMS_1         NUMBER(17,2),
  CFOP_SAIDA_ORIGEM       VARCHAR2(4 BYTE),
  CST_ORIGEM              VARCHAR2(10 BYTE),
  F_ROWID                 ROWID
)
ON COMMIT PRESERVE ROWS
NOCACHE
/


Prompt Index IDX_X07_DOCTO_FISCAL_GTT;
--
-- IDX_X07_DOCTO_FISCAL_GTT  (Index) 
--
CREATE INDEX IDX_X07_DOCTO_FISCAL_GTT ON MSAFI.X07_DOCTO_FISCAL_GTT
(COD_EMPRESA, COD_ESTAB, DATA_FISCAL, MOVTO_E_S, NORM_DEV, 
IDENT_DOCTO, IDENT_FIS_JUR, NUM_DOCFIS, SERIE_DOCFIS, SUB_SERIE_DOCFIS)
/
