Prompt Table DPSP_FIN048_RET_NF_ENT;
--
-- DPSP_FIN048_RET_NF_ENT  (Table) 
--
CREATE TABLE MSAFI.DPSP_FIN048_RET_NF_ENT
(
  COD_EMPRESA             VARCHAR2(3 BYTE)      NOT NULL,
  COD_ESTAB               VARCHAR2(6 BYTE)      NOT NULL,
  DATA_FISCAL             DATE                  NOT NULL,
  NUM_DOCFIS              VARCHAR2(12 BYTE)     NOT NULL,
  NUM_AUTENTIC_NFE        VARCHAR2(80 BYTE),
  COD_FIS_JUR             VARCHAR2(14 BYTE),
  CPF_CGC                 VARCHAR2(14 BYTE),
  COD_DOCTO               VARCHAR2(5 BYTE),
  COD_MODELO              VARCHAR2(2 BYTE),
  COD_CFO                 VARCHAR2(4 BYTE),
  NATUREZA_OPERACAO       VARCHAR2(3 BYTE),
  COD_PRODUTO             VARCHAR2(35 BYTE),
  DESCRICAO               VARCHAR2(50 BYTE),
  CST_A                   CHAR(2 BYTE),
  CST_B                   CHAR(2 BYTE),
  QUANTIDADE              NUMBER(17,6),
  NCM                     VARCHAR2(10 BYTE),
  NUM_ITEM                NUMBER(5),
  VLR_CONTABIL_ITEM       NUMBER(17,2),
  VLR_ITEM                NUMBER(17,2),
  VLR_BASE_ICMS_1         NUMBER(17,2),
  VLR_ALIQUOTA            NUMBER(7,4),
  VLR_ICMS_PROPRIO        NUMBER(17,2),
  VLR_BASE_ICMS_2         NUMBER(17,2),
  VLR_BASE_ICMS_3         NUMBER(17,2),
  CFOP_SAIDA_ORIGEM       VARCHAR2(4 BYTE),
  CFOP_ENTRADA_ORIGEM     VARCHAR2(4 BYTE),
  VALOR_BASE_ICMS_ORIGEM  NUMBER,
  VALOR_ALIQUOTA_ORIGEM   NUMBER,
  VALOR_ICMS_ORIGEM       NUMBER,
  CST_ORIGEM              VARCHAR2(10 BYTE),
  NUM_CONTROLE_DOCTO      VARCHAR2(12 BYTE),
  PROC_ID                 INTEGER,
  NM_USUARIO              VARCHAR2(50 BYTE),
  DT_CARGA                VARCHAR2(20 BYTE),
  STATUS                  VARCHAR2(10 BYTE)
)
LOGGING 
ROW STORE COMPRESS BASIC
NOCACHE
MONITORING
/


Prompt Index IDX_PRODUTO;
--
-- IDX_PRODUTO  (Index) 
--
CREATE INDEX IDX_PRODUTO ON MSAFI.DPSP_FIN048_RET_NF_ENT
(COD_PRODUTO)
LOGGING
/

Prompt Index PK_FIN048;
--
-- PK_FIN048  (Index) 
--
CREATE UNIQUE INDEX MSAF.PK_FIN048 ON MSAFI.DPSP_FIN048_RET_NF_ENT
(COD_EMPRESA, COD_ESTAB, DATA_FISCAL, NUM_DOCFIS, NUM_ITEM)
LOGGING
/
