Prompt Table DPSP_MSAF_FIN048_XML_GTT;
--
-- DPSP_MSAF_FIN048_XML_GTT  (Table) 
--
CREATE GLOBAL TEMPORARY TABLE MSAFI.DPSP_MSAF_FIN048_XML_GTT
(
  COD_EMPRESA       VARCHAR2(3 BYTE),
  COD_ESTAB         VARCHAR2(6 BYTE),
  DATA_FISCAL       DATE,
  MOVTO_E_S         CHAR(1 BYTE),
  NORM_DEV          CHAR(1 BYTE),
  IDENT_DOCTO       NUMBER(12),
  IDENT_FIS_JUR     NUMBER(12),
  NUM_DOCFIS        VARCHAR2(12 BYTE),
  SERIE_DOCFIS      VARCHAR2(3 BYTE),
  SUB_SERIE_DOCFIS  VARCHAR2(2 BYTE),
  DISCRI_ITEM       VARCHAR2(46 BYTE),
  NUM_AUTENTIC_NFE  VARCHAR2(80 BYTE),
  COD_PRODUTO       VARCHAR2(35 BYTE),
  CFO_BRL_CD        VARCHAR2(10 BYTE),
  VLR_BASE_ICMS     NUMBER,
  VLR_ICMS          NUMBER,
  VLR_ICMS_ST       NUMBER,
  COD_PROCESSO      INTEGER,
  PROC_ID           INTEGER,
  DT_CARGA          DATE
)
ON COMMIT PRESERVE ROWS
NOCACHE
/


Prompt Index IDX01_DPSP_MSAF_FIN048_XML_GTT;
--
-- IDX01_DPSP_MSAF_FIN048_XML_GTT  (Index) 
--
CREATE INDEX IDX01_DPSP_MSAF_FIN048_XML_GTT ON MSAFI.DPSP_MSAF_FIN048_XML_GTT
(COD_EMPRESA, COD_ESTAB, DATA_FISCAL, MOVTO_E_S, NORM_DEV, 
IDENT_DOCTO, IDENT_FIS_JUR, NUM_DOCFIS, SERIE_DOCFIS, SUB_SERIE_DOCFIS, 
DISCRI_ITEM)
/
